2023-11-10 20:52:08,299 - [ERROR] - Internal Server Error: /admin/news/new/add/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'kombu.exceptions.OperationalError'>, OperationalError('Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.'), <traceback object at 0x00000286D0022280>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 264, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 265, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 627, in _connect
    raise err
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 615, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 127, in reconnect_on_error
    yield
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 177, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\client.py", line 916, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\client.py", line 749, in execute_command
    self.connection = self.connection_pool.get_connection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 1086, in get_connection
    connection.connect()
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 264, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 265, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 627, in _connect
    raise err
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 615, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\kombu\connection.py", line 472, in _reraise_as_library_errors
    yield
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\app\base.py", line 797, in send_task
    self.backend.on_task_call(P, task_id)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 373, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 169, in consume_from
    return self.start(task_id)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 147, in start
    self._consume_from(initial_task_id)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 176, in _consume_from
    with self.reconnect_on_error():
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 130, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 384, in ensure
    return retry_over_time(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\kombu\utils\functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 106, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\commands\core.py", line 2015, in mget
    return self.execute_command("MGET", *args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\client.py", line 533, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 1086, in get_connection
    connection.connect()
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\options.py", line 1227, in save_model
    obj.save()
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\models\base.py", line 892, in save_base
    post_save.send(
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\project\news\signals.py", line 20, in New_created
    with_every_new_post.delay(instance.category.title,
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\app\task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\app\task.py", line 594, in apply_async
    return app.send_task(
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\app\base.py", line 795, in send_task
    with P.connection._reraise_as_library_errors():
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\kombu\connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
2023-11-10 20:52:08,308 - [ERROR] - "POST /admin/news/new/add/ HTTP/1.1" 500 334266 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-11-10 20:59:54,738 - [ERROR] - Internal Server Error: /admin/news/new/add/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'kombu.exceptions.OperationalError'>, OperationalError('Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.'), <traceback object at 0x00000286D1B9AD00>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 442, in send_packed_command
    self._sock.sendall(item)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 127, in reconnect_on_error
    yield
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 177, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\client.py", line 916, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\client.py", line 761, in execute_command
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\client.py", line 800, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\retry.py", line 49, in call_with_retry
    fail(error)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\client.py", line 802, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\client.py", line 789, in _disconnect_raise_connect
    raise error
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\client.py", line 801, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 464, in send_command
    self.send_packed_command(
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 453, in send_packed_command
    raise ConnectionError(f"Error {errno} while writing to socket. {errmsg}.")
redis.exceptions.ConnectionError: Error 10054 while writing to socket. Удаленный хост принудительно разорвал существующее подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 264, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 265, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 627, in _connect
    raise err
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 615, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\kombu\connection.py", line 472, in _reraise_as_library_errors
    yield
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\app\base.py", line 797, in send_task
    self.backend.on_task_call(P, task_id)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 373, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 170, in consume_from
    self._consume_from(task_id)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 176, in _consume_from
    with self.reconnect_on_error():
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 130, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 384, in ensure
    return retry_over_time(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\kombu\utils\functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\backends\redis.py", line 106, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\commands\core.py", line 2015, in mget
    return self.execute_command("MGET", *args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\client.py", line 533, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 1086, in get_connection
    connection.connect()
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\redis\connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\contrib\admin\options.py", line 1227, in save_model
    obj.save()
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\models\base.py", line 892, in save_base
    post_save.send(
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\project\news\signals.py", line 20, in New_created
    with_every_new_post.delay(instance.category.title,
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\app\task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\app\task.py", line 594, in apply_async
    return app.send_task(
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\celery\app\base.py", line 795, in send_task
    with P.connection._reraise_as_library_errors():
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\kombu\connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
2023-11-10 20:59:54,742 - [ERROR] - "POST /admin/news/new/add/ HTTP/1.1" 500 339858 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 20:57:43,220 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399C47B40>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-12-03 20:57:43,236 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 169649 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 22:45:55,313 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399E23580>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-12-03 22:45:55,324 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 169804 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 22:46:37,998 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399DFA040>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-12-03 22:46:38,008 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 169894 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 22:47:51,365 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399E290C0>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-12-03 22:47:51,375 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 169601 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 22:54:18,803 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399DAFE00>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-12-03 22:54:18,815 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 169605 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 23:33:05,299 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399F3FE40>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-12-03 23:33:05,311 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 169836 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 23:33:20,379 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 4: 'trans'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399EA2B80>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'trans'. Did you forget to register or load this tag?
2023-12-03 23:33:20,389 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 153142 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 23:33:54,366 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399EA1880>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-12-03 23:33:54,377 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 169836 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 23:34:57,643 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 4: 'Главная', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399D4D0C0>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'Главная'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'Главная', expected 'endblock'. Did you forget to register or load this tag?
2023-12-03 23:34:57,653 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 169839 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 23:39:28,459 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 9: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399F3D200>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-12-03 23:39:28,471 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 168709 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-03 23:40:05,211 - [ERROR] - Internal Server Error: /news/news_list/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 9: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000018399DAE580>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2023-12-03 23:40:05,223 - [ERROR] - "GET /news/news_list/ HTTP/1.1" 500 168709 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-09 13:23:34,784 - [ERROR] - Internal Server Error: /news/search/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_category.title_en_us'), <traceback object at 0x00000280C0C0CB00>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: news_category.title_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 715, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 847, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 914, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\utils.py", line 84, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\utils.py", line 75, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\widgets.py", line 758, in get_context
    context = super().get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\widgets.py", line 717, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\widgets.py", line 657, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django_filters\fields.py", line 246, in __iter__
    yield from iterable
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\models.py", line 1403, in __iter__
    for obj in queryset:
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\models\query.py", line 516, in _iterator
    yield from iterable
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: news_category.title_en_us
2023-12-09 13:23:34,824 - [ERROR] - "GET /news/search/ HTTP/1.1" 500 328438 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2023-12-09 13:23:50,025 - [ERROR] - Internal Server Error: /news/create/ - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\log.py - (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_category.title_en_us'), <traceback object at 0x00000280C0D389C0>) 
Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: news_category.title_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\template\base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\widgets.py", line 758, in get_context
    context = super().get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\widgets.py", line 717, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\widgets.py", line 657, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\forms\models.py", line 1403, in __iter__
    for obj in queryset:
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\models\query.py", line 516, in _iterator
    yield from iterable
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: news_category.title_en_us
2023-12-09 13:23:50,043 - [ERROR] - "GET /news/create/ HTTP/1.1" 500 265606 - C:\Users\Acer\PycharmProjects\PythonProjects\test_progect\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
